### ISSUE TITLE
Getting error No such module 'Activity Kit'

### ISSUE THREAD

**Issue by yash-vaghela21** [rodrigo2392/react-native-dynamic-island#1]
Hello
I was trying this to see how it works and look but i am getting below error.

![Screenshot 2022-11-25 at 10 08 04 AM](https://user-images.githubusercontent.com/37238045/203902862-d1b7f498-457e-4273-82a5-b514700f3682.png)

**Comment by Nishit-Chauhan** [comment]
@ydv0121 facing the same on my side as well.

**Comment by rodrigo2392** [comment]
Hey guys do you have xcode 14.1 or above?

**Comment by Nishit-Chauhan** [comment]
@rodrigo2392 tried on Xcode 14.0

**Comment by rodrigo2392** [comment]
Also remember set at least ios 14.0 as target on your project

**Comment by rodrigo2392** [comment]
> @rodrigo2392 tried on Xcode 14.0 
You need xcode 14.1 please update and try again

**Comment by yash-vaghela21** [comment]
@rodrigo2392 ohk let me try it 
i did clone your project and run it and getting this error.
let me know if i missed anything

**Comment by rodrigo2392** [comment]
> @rodrigo2392 ohk let me try it 
> 
> i did clone your project and run it and getting this error.
> 
> let me know if i missed anything

Please try with xcode 14.1 and ios target 14.0 let me know if you have the same issue
